[settings]
idiomatic_version_file_enable_tools = ["node", "python"]
minimum_release_age_excludes = [
  "aqua:anthropics/claude-code",
  "aqua:openai/codex",
]

[tools]
"aqua:anthropics/claude-code" = "latest"
"aqua:dlvhdr/gh-dash" = "latest"
"aqua:ollama/ollama" = "latest"
"aqua:openai/codex" = "latest"
"aqua:tree-sitter/tree-sitter" = "latest"
"aqua:vercel-labs/agent-browser" = "latest"
bun = "latest"
deno = "latest"
dotnet = "10"
"github:tmuxpack/tpack" = "latest"
"github:yt-dlp/yt-dlp" = "latest"
java = "lts"
markdownlint-cli2 = "latest"
node = "lts"
"npm:@playwright/cli" = { version = "latest", trust_policy_excludes = ["@playwright/cli@0.1.19", "playwright@1.63.0-alpha-2026-08-31", "playwright-core@1.63.0-alpha-2026-08-31"] }
"npm:@code-yeongyu/comment-checker" = "latest"
"npm:@luisurrutia/bird" = "1.0.0"
"npm:clawpatch" = "latest"
"npm:skills" = "latest"
opencode = "latest"
"pipx:httpie" = "latest"
"pipx:pre-commit" = { version = "latest", uvx_args = "--with pre-commit-uv" }
pnpm = "latest"
python = "3"
uv = "latest"
