[settings]
idiomatic_version_file_enable_tools = ["node", "python"]

[tools]
"aqua:vercel-labs/agent-browser" = "latest"
bun = "latest"
java = "lts"
markdownlint-cli2 = "latest"
node = "lts"
pnpm = "latest"
python = "3"
uv = "latest"
