complete -c claude -n __fish_use_subcommand -l add-dir -r -d "Add directories that Claude can access"
complete -c claude -n __fish_use_subcommand -l agent -r -d "Select an agent for the session"
complete -c claude -n __fish_use_subcommand -l agents -r -d "Define custom agents as JSON"
complete -c claude -n __fish_use_subcommand -l allow-dangerously-skip-permissions -d "Allow bypassing permission checks"
complete -c claude -n __fish_use_subcommand -l allowedTools -r -d "Allow specific tools"
complete -c claude -n __fish_use_subcommand -l allowed-tools -r -d "Allow specific tools"
complete -c claude -n __fish_use_subcommand -l append-system-prompt -r -d "Append to the default system prompt"
complete -c claude -n __fish_use_subcommand -l autocompact -r -a auto -d "Set the auto-compact window size"
complete -c claude -n __fish_use_subcommand -l ax-screen-reader -d "Use screen-reader-friendly rendering"
complete -c claude -n __fish_use_subcommand -l bg -d "Start as a background agent"
complete -c claude -n __fish_use_subcommand -l background -d "Start as a background agent"
complete -c claude -n __fish_use_subcommand -l bare -d "Start with minimal integrations"
complete -c claude -n __fish_use_subcommand -l betas -r -d "Enable beta headers"
complete -c claude -n __fish_use_subcommand -l brief -d "Enable agent-to-user messages"
complete -c claude -n __fish_use_subcommand -l chrome -d "Enable Claude in Chrome"
complete -c claude -n __fish_use_subcommand -l cloud -r -d "Create or attach to a cloud session"
complete -c claude -n __fish_use_subcommand -s c -l continue -d "Continue the most recent conversation"
complete -c claude -n __fish_use_subcommand -l dangerously-skip-permissions -d "Bypass permission checks"
complete -c claude -n __fish_use_subcommand -s d -l debug -r -d "Enable debug output"
complete -c claude -n __fish_use_subcommand -l debug-file -rF -d "Write debug output to a file"
complete -c claude -n __fish_use_subcommand -l disable-slash-commands -d "Disable skills"
complete -c claude -n __fish_use_subcommand -l disallowedTools -r -d "Deny specific tools"
complete -c claude -n __fish_use_subcommand -l disallowed-tools -r -d "Deny specific tools"
complete -c claude -n __fish_use_subcommand -l effort -r -a "low medium high xhigh max" -d "Set the effort level"
complete -c claude -n __fish_use_subcommand -l environment -r -d "Use a self-hosted cloud environment"
complete -c claude -n __fish_use_subcommand -l exclude-dynamic-system-prompt-sections -d "Move dynamic system prompt sections to the first message"
complete -c claude -n __fish_use_subcommand -l fallback-model -r -d "Select fallback models"
complete -c claude -n __fish_use_subcommand -l file -rF -d "Download a file resource"
complete -c claude -n __fish_use_subcommand -l fork-session -d "Create a new session when resuming"
complete -c claude -n __fish_use_subcommand -l forward-subagent-text -d "Forward subagent text and thinking blocks"
complete -c claude -n __fish_use_subcommand -l from-pr -r -d "Resume a session linked to a pull request"
complete -c claude -n __fish_use_subcommand -s h -l help -d "Display help"
complete -c claude -n __fish_use_subcommand -l ide -d "Connect to an IDE"
complete -c claude -n __fish_use_subcommand -l include-hook-events -d "Include hook lifecycle events"
complete -c claude -n __fish_use_subcommand -l include-partial-messages -d "Include partial streaming messages"
complete -c claude -n __fish_use_subcommand -l input-format -r -a "text stream-json" -d "Set the input format"
complete -c claude -n __fish_use_subcommand -l json-schema -rF -d "Validate output with a JSON schema"
complete -c claude -n __fish_use_subcommand -l max-budget-usd -r -d "Set the maximum API budget"
complete -c claude -n __fish_use_subcommand -l mcp-config -rF -d "Load MCP server configuration"
complete -c claude -n __fish_use_subcommand -l model -r -a "fable opus sonnet" -d "Select the model"
complete -c claude -n __fish_use_subcommand -s n -l name -r -d "Name the session"
complete -c claude -n __fish_use_subcommand -l no-chrome -d "Disable Claude in Chrome"
complete -c claude -n __fish_use_subcommand -l no-session-persistence -d "Do not save the session"
complete -c claude -n __fish_use_subcommand -l output-format -r -a "text json stream-json" -d "Set the output format"
complete -c claude -n __fish_use_subcommand -l permission-mode -r -a "acceptEdits auto bypassPermissions manual dontAsk plan" -d "Set the permission mode"
complete -c claude -n __fish_use_subcommand -l plugin-dir -rF -d "Load plugins from a directory"
complete -c claude -n __fish_use_subcommand -l plugin-url -r -d "Load a plugin from a URL"
complete -c claude -n __fish_use_subcommand -s p -l print -d "Print the response and exit"
complete -c claude -n __fish_use_subcommand -l prompt-suggestions -r -d "Control prompt suggestions"
complete -c claude -n __fish_use_subcommand -l remote-control -r -d "Start with remote control enabled"
complete -c claude -n __fish_use_subcommand -l remote-control-session-name-prefix -r -d "Prefix remote-control session names"
complete -c claude -n __fish_use_subcommand -l replay-user-messages -d "Replay stdin messages on stdout"
complete -c claude -n __fish_use_subcommand -s r -l resume -r -d "Resume a conversation"
complete -c claude -n __fish_use_subcommand -l safe-mode -d "Disable customizations for the session"
complete -c claude -n __fish_use_subcommand -l session-id -r -d "Use a specific session ID"
complete -c claude -n __fish_use_subcommand -l setting-sources -r -a "user project local" -d "Select setting sources"
complete -c claude -n __fish_use_subcommand -l settings -rF -d "Load settings from JSON or a file"
complete -c claude -n __fish_use_subcommand -l strict-mcp-config -d "Use only explicit MCP configuration"
complete -c claude -n __fish_use_subcommand -l system-prompt -r -d "Replace the system prompt"
complete -c claude -n __fish_use_subcommand -l teleport -r -d "Resume a teleport session"
complete -c claude -n __fish_use_subcommand -l tmux -d "Create a tmux worktree session"
complete -c claude -n __fish_use_subcommand -l tools -r -d "Set the available tools"
complete -c claude -n __fish_use_subcommand -l verbose -d "Enable verbose output"
complete -c claude -n __fish_use_subcommand -s v -l version -d "Display the version"
complete -c claude -n __fish_use_subcommand -s w -l worktree -r -d "Create a git worktree"

complete -c claude -n __fish_use_subcommand -f -a agents -d "Manage background agents"
complete -c claude -n __fish_use_subcommand -f -a auth -d "Manage authentication"
complete -c claude -n __fish_use_subcommand -f -a auto-mode -d "Manage auto mode"
complete -c claude -n __fish_use_subcommand -f -a doctor -d "Check the installation"
complete -c claude -n __fish_use_subcommand -f -a gateway -d "Run the enterprise gateway"
complete -c claude -n __fish_use_subcommand -f -a import -d "Import another agent's configuration"
complete -c claude -n __fish_use_subcommand -f -a install -d "Install the native build"
complete -c claude -n __fish_use_subcommand -f -a mcp -d "Manage MCP servers"
complete -c claude -n __fish_use_subcommand -f -a plugin -d "Manage plugins"
complete -c claude -n __fish_use_subcommand -f -a plugins -d "Manage plugins"
complete -c claude -n __fish_use_subcommand -f -a project -d "Manage project state"
complete -c claude -n __fish_use_subcommand -f -a setup-token -d "Create a long-lived authentication token"
complete -c claude -n __fish_use_subcommand -f -a ultrareview -d "Run a cloud code review"
complete -c claude -n __fish_use_subcommand -f -a update -d "Update Claude Code"
complete -c claude -n __fish_use_subcommand -f -a upgrade -d "Update Claude Code"
