add_newline = false

format = """
$shlvl\
$kubernetes\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$docker_context\
$package\
$elm\
$golang\
$helm\
$java\
$kotlin\
$gradle\
$lua\
$nodejs\
$opa\
$perl\
$php\
$python\
$ruby\
$rust\
$scala\
$solidity\
$swift\
$terraform\
$memory_usage\
$aws\
$gcloud\
$openstack\
$azure\
$direnv\
$env_var\
$custom\
$sudo\
$cmd_duration\
$jobs\
$battery\
$time\
$status\
$os\
$container\
$shell\
$character"""

[ruby]
disabled = true

[gcloud]
disabled = true

[buf]
disabled = true

[time]
disabled = false
time_format = '%R'
time_range = '18:30:00-09:00:00'

